# Generated by Django 3.2 on 2021-05-07 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import homeworks.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='UserHomework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.PositiveIntegerField(default=0)),
                ('homework', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='homeworks.homework')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserHomeworkAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=homeworks.models.rename_file)),
                ('user_homework', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='homeworks.userhomework')),
            ],
        ),
        migrations.CreateModel(
            name='UserHomoworkAnswerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.PositiveIntegerField(default=0)),
                ('review_description', models.TextField(null=True)),
                ('user_homework_answer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='homeworks.userhomeworkanswer')),
            ],
        ),
    ]
